export const Typography = {
  weight: {
    thin: 'dfc-font-thin',
    extralight: 'dfc-font-extralight',
    light: 'dfc-font-light',
    normal: 'dfc-font-normal',
    medium: 'dfc-font-medium',
    semibold: 'dfc-font-semibold',
    bold: 'dfc-font-bold',
    extrabold: 'dfc-font-extrabold',
    black: 'dfc-font-black',
  },
  size: {
    xs: 'dfc-text-xs',
    sm: 'dfc-text-sm',
    base: 'dfc-text-base',
    lg: 'dfc-text-lg',
    xl: 'dfc-text-xl',
    '2xl': 'dfc-text-2xl',
    '3xl': 'dfc-text-3xl',
    '4xl': 'dfc-text-4xl',
    '5xl': 'dfc-text-5xl',
    '6xl': 'dfc-text-6xl',
    '7xl': 'dfc-text-7xl',
    '8xl': 'dfc-text-8xl',
    '9xl': 'dfc-text-9xl',
  },
  decoration: {
    lineThrough: 'dfc-line-through',
    underline: 'dfc-underline',
    uppercase: 'dfc-uppercase',
  },
  leading: {
    none: 'dfc-leading-none',
    normal: 'dfc-leading-normal',
    loose: 'dfc-leading-loose',
  },
};
