"""empty message

Revision ID: 7b5b3c4ae3aa
Revises: 9169ef277690
Create Date: 2022-12-06 09:30:50.156940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b5b3c4ae3aa'
down_revision = '9169ef277690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_notification',
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alert_level', sa.String(length=100), nullable=False),
    sa.Column('duration_in_mins', sa.Integer(), nullable=False),
    sa.Column('last_sent_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_level', 'integration_id', name='secret_notification_constraint')
    )
    op.drop_column('cloud_compliance_node', 'version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_compliance_node', sa.Column('version', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_table('secret_notification')
    # ### end Alembic commands ###
